### ISSUE TITLE
Unable to get this working...

### ISSUE THREAD

**Issue by Sjack1209** [IRTrail/Orca-Slicer-Post-Processing-Scripts#1]
Hey, hoping you can help me troubleshoot why this isn't working for me.  Here's a screenshot of what I put in the "post processing" section of Orca.  I've also attached a file that I tried using this on, but it didn't work. (I had to convert it to a .txt to upload it here)

![image](https://github.com/user-attachments/assets/19f57ec1-29ea-40c2-94d8-9ea9df42afb8)

[OrcaCube_ABS_1h58m.txt](https://github.com/user-attachments/files/17142382/OrcaCube_ABS_1h58m.txt)

**Comment by IRTrail** [comment]
I made a change. See if that works better.

**Comment by Sjack1209** [comment]
You rock! that worked perfectly!  Seriously appreciate what you and people like yourself bring to this community!
